[package]
name = "sysusage"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.20.4"
pretty_env_logger = "0.4.0"
log = "0.4.14"
clap = "3.0.0-beta.5"